package(default_visibility = ["//visibility:public"])

load("@io_bazel_rules_go//go:def.bzl", "go_prefix", "go_library", "go_test", "go_binary")

#go_binary(
#    name = "go_default_library",
#    srcs = [
#        "main.go",
#        "generator.go"
#    ],
#    deps = [
#        "@com_github_golang_protobuf//proto:go_default_library",
#        "@com_github_googleapis_googleapis//:google/rpc",
#        "@com_github_hashicorp_go_multierror//:go_default_library",
#        "@com_github_spf13_cobra//:go_default_library",
#    ],
#)

#go_test(
#    name = "small_tests",
#    size = "small",
#    srcs = [
#        "applicationLogs_test.go",
#        "builder_test.go",
#        "configError_test.go",
#        "metrics_test.go",
#    ],
#    library = ":go_default_library",
#)
