// POST PROCESSED USING by build_cfg.sh
// 84100219 5669 mixer/v1/config/cfg.proto
// Code generated by protoc-gen-go.
// source: mixer/v1/config/cfg.proto
// DO NOT EDIT!

/*
Package istio_mixer_v1_config is a generated protocol buffer package.

It is generated from these files:
	mixer/v1/config/cfg.proto

It has these top-level messages:
	ServiceConfig
	AspectRule
	Aspect
	Adapter
	GlobalConfig
	ClientConfig
	Uri
	IpAddress
	DnsName
	EmailAddress
*/
package istio_mixer_v1_config

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import istio_mixer_v1_config_descriptor2 "istio.io/api/mixer/v1/config/descriptor"
import istio_mixer_v1_config_descriptor3 "istio.io/api/mixer/v1/config/descriptor"
import istio_mixer_v1_config_descriptor4 "istio.io/api/mixer/v1/config/descriptor"
import istio_mixer_v1_config_descriptor5 "istio.io/api/mixer/v1/config/descriptor"
import istio_mixer_v1_config_descriptor6 "istio.io/api/mixer/v1/config/descriptor"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Configures a set of services
// following example configures metrics collection and ratelimit for
// all services
// # service config
// subject: "namespace:ns1"
// revision: "1011"
// rules:
// - selector: target_name == "*"
//  aspects:
//  - kind: metrics
//    params:
//      metrics:   # defines metric collection across the board.
//      - name: response_time_by_status_code
//        value: metric.response_time     # certain attributes are metrics
//        metric_kind: DELTA
//        labels:
//        - key: response.status_code
//  - kind: ratelimiter
//    params:
//      limits:  # imposes 2 limits, 100/s per source and destination
//      - limit: "100/s"
//        labels:
//          - key: src.service_id
//          - key: target.service_id
//       - limit: "1000/s"  # every destination service gets 1000/s
//        labels:
//          - key: target.service_id
type ServiceConfig struct {
	// subject is unique for a config type
	// 2 config with the same subject will overwrite each other
	Subject string `protobuf:"bytes,1,opt,name=subject" json:"subject,omitempty"`
	// revision of this config. This is assigned by the server
	Revision string        `protobuf:"bytes,2,opt,name=revision" json:"revision,omitempty"`
	Rules    []*AspectRule `protobuf:"bytes,3,rep,name=rules" json:"rules,omitempty"`
}

func (m *ServiceConfig) Reset()                    { *m = ServiceConfig{} }
func (m *ServiceConfig) String() string            { return proto.CompactTextString(m) }
func (*ServiceConfig) ProtoMessage()               {}
func (*ServiceConfig) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ServiceConfig) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *ServiceConfig) GetRevision() string {
	if m != nil {
		return m.Revision
	}
	return ""
}

func (m *ServiceConfig) GetRules() []*AspectRule {
	if m != nil {
		return m.Rules
	}
	return nil
}

// AspectRules are intent based
type AspectRule struct {
	// selector is an attributes based predicate.
	// attr1 == "20" && attr2 == "30"
	Selector string `protobuf:"bytes,1,opt,name=selector" json:"selector,omitempty"`
	// The following aspects apply when the selector predicate evaluates to True
	Aspects []*Aspect `protobuf:"bytes,2,rep,name=aspects" json:"aspects,omitempty"`
	// Nested aspect Rule is evaluated if selector predicate evaluates to True
	Rules []*AspectRule `protobuf:"bytes,3,rep,name=rules" json:"rules,omitempty"`
}

func (m *AspectRule) Reset()                    { *m = AspectRule{} }
func (m *AspectRule) String() string            { return proto.CompactTextString(m) }
func (*AspectRule) ProtoMessage()               {}
func (*AspectRule) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AspectRule) GetSelector() string {
	if m != nil {
		return m.Selector
	}
	return ""
}

func (m *AspectRule) GetAspects() []*Aspect {
	if m != nil {
		return m.Aspects
	}
	return nil
}

func (m *AspectRule) GetRules() []*AspectRule {
	if m != nil {
		return m.Rules
	}
	return nil
}

// Aspect is intent based. It specifies the intent "kind"
// following example specifies that the user would like to collect
// response_time with 3 labels (src_consumer_id, target_response_status_code,
// target_service_name)
//
// The Input section tells if target_service_name is not available it can be
// computed using the given expression
//
//      kind: istio/metrics
//      params:
//        metrics:
//        - name: response_time     # What to call this metric outbound.
//          value: metric_response_time  # from wellknown vocabulary
//          metric_kind: DELTA
//          labels:
//          - key: src_consumer_id
//          - key: target_response_status_code
//          - key: target_service_name
//      Inputs:
//           Attr.target_service_name: target_service_name || target_service_id
type Aspect struct {
	Kind    string `protobuf:"bytes,1,opt,name=kind" json:"kind,omitempty"`
	Adapter string `protobuf:"bytes,2,opt,name=adapter" json:"adapter,omitempty"`
	// maps from isio Attribute space to aspect.Input proto defined
	// by the aspect
	Inputs map[string]string `protobuf:"bytes,3,rep,name=inputs" json:"inputs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Struct representation of a proto defined by the aspect
	Params interface{} `protobuf:"bytes,4,opt,name=params" json:"params,omitempty"`
	Name   string      `protobuf:"bytes,5,opt,name=name" json:"name,omitempty"`
}

func (m *Aspect) Reset()                    { *m = Aspect{} }
func (m *Aspect) String() string            { return proto.CompactTextString(m) }
func (*Aspect) ProtoMessage()               {}
func (*Aspect) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Aspect) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *Aspect) GetAdapter() string {
	if m != nil {
		return m.Adapter
	}
	return ""
}

func (m *Aspect) GetInputs() map[string]string {
	if m != nil {
		return m.Inputs
	}
	return nil
}

func (m *Aspect) GetParams() interface{} {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *Aspect) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// Adapter config defines specifics of adapter implementations
// We define an adapter that provides "metrics" aspect
// Kind: istio/metrics
// Name: metrics-statsd
// Impl: “istio.io/adapters/statsd”
// Args:
//    Host: statd.svc.cluster
//    Port: 8125
type Adapter struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Kind string `protobuf:"bytes,2,opt,name=kind" json:"kind,omitempty"`
	Impl string `protobuf:"bytes,3,opt,name=impl" json:"impl,omitempty"`
	// Struct representation of a proto defined by the implementation
	Params interface{} `protobuf:"bytes,4,opt,name=params" json:"params,omitempty"`
}

func (m *Adapter) Reset()                    { *m = Adapter{} }
func (m *Adapter) String() string            { return proto.CompactTextString(m) }
func (*Adapter) ProtoMessage()               {}
func (*Adapter) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Adapter) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Adapter) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *Adapter) GetImpl() string {
	if m != nil {
		return m.Impl
	}
	return ""
}

func (m *Adapter) GetParams() interface{} {
	if m != nil {
		return m.Params
	}
	return nil
}

// GlobalConfig defines configuration elements that are available
// for the rest of the config
// It is used to configure adapters and make them available in AspectRules
type GlobalConfig struct {
	Revision string     `protobuf:"bytes,1,opt,name=revision" json:"revision,omitempty"`
	Adapters []*Adapter `protobuf:"bytes,2,rep,name=adapters" json:"adapters,omitempty"`
	// TODO: remove these in https://github.com/istio/api/pull/45
	Logs               []*istio_mixer_v1_config_descriptor2.LogEntryDescriptor          `protobuf:"bytes,3,rep,name=logs" json:"logs,omitempty"`
	Metrics            []*istio_mixer_v1_config_descriptor3.MetricDescriptor            `protobuf:"bytes,4,rep,name=metrics" json:"metrics,omitempty"`
	MonitoredResources []*istio_mixer_v1_config_descriptor4.MonitoredResourceDescriptor `protobuf:"bytes,5,rep,name=monitored_resources" json:"monitored_resources,omitempty"`
	Principals         []*istio_mixer_v1_config_descriptor5.PrincipalDescriptor         `protobuf:"bytes,6,rep,name=principals" json:"principals,omitempty"`
	Quotas             []*istio_mixer_v1_config_descriptor6.QuotaDescriptor             `protobuf:"bytes,7,rep,name=quotas" json:"quotas,omitempty"`
}

func (m *GlobalConfig) Reset()                    { *m = GlobalConfig{} }
func (m *GlobalConfig) String() string            { return proto.CompactTextString(m) }
func (*GlobalConfig) ProtoMessage()               {}
func (*GlobalConfig) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *GlobalConfig) GetRevision() string {
	if m != nil {
		return m.Revision
	}
	return ""
}

func (m *GlobalConfig) GetAdapters() []*Adapter {
	if m != nil {
		return m.Adapters
	}
	return nil
}

func (m *GlobalConfig) GetLogs() []*istio_mixer_v1_config_descriptor2.LogEntryDescriptor {
	if m != nil {
		return m.Logs
	}
	return nil
}

func (m *GlobalConfig) GetMetrics() []*istio_mixer_v1_config_descriptor3.MetricDescriptor {
	if m != nil {
		return m.Metrics
	}
	return nil
}

func (m *GlobalConfig) GetMonitoredResources() []*istio_mixer_v1_config_descriptor4.MonitoredResourceDescriptor {
	if m != nil {
		return m.MonitoredResources
	}
	return nil
}

func (m *GlobalConfig) GetPrincipals() []*istio_mixer_v1_config_descriptor5.PrincipalDescriptor {
	if m != nil {
		return m.Principals
	}
	return nil
}

func (m *GlobalConfig) GetQuotas() []*istio_mixer_v1_config_descriptor6.QuotaDescriptor {
	if m != nil {
		return m.Quotas
	}
	return nil
}

// ClientConfig defines configuration from a client perspective.
// ServiceA can define rules about what happens when it is acting as client
// to other services
type ClientConfig struct {
	Subject  string        `protobuf:"bytes,1,opt,name=subject" json:"subject,omitempty"`
	Revision string        `protobuf:"bytes,2,opt,name=revision" json:"revision,omitempty"`
	Rules    []*AspectRule `protobuf:"bytes,3,rep,name=rules" json:"rules,omitempty"`
}

func (m *ClientConfig) Reset()                    { *m = ClientConfig{} }
func (m *ClientConfig) String() string            { return proto.CompactTextString(m) }
func (*ClientConfig) ProtoMessage()               {}
func (*ClientConfig) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ClientConfig) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *ClientConfig) GetRevision() string {
	if m != nil {
		return m.Revision
	}
	return ""
}

func (m *ClientConfig) GetRules() []*AspectRule {
	if m != nil {
		return m.Rules
	}
	return nil
}

// Uri represents a properly formed URI.
type Uri struct {
	Value string `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
}

func (m *Uri) Reset()                    { *m = Uri{} }
func (m *Uri) String() string            { return proto.CompactTextString(m) }
func (*Uri) ProtoMessage()               {}
func (*Uri) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Uri) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// IpAddress holds an IPv4 or IPv6 address.
type IpAddress struct {
	Value []byte `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *IpAddress) Reset()                    { *m = IpAddress{} }
func (m *IpAddress) String() string            { return proto.CompactTextString(m) }
func (*IpAddress) ProtoMessage()               {}
func (*IpAddress) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *IpAddress) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

// DnsName holds a valid domain name.
type DnsName struct {
	Value string `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
}

func (m *DnsName) Reset()                    { *m = DnsName{} }
func (m *DnsName) String() string            { return proto.CompactTextString(m) }
func (*DnsName) ProtoMessage()               {}
func (*DnsName) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *DnsName) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// EmailAddress holds a properly formatted email address.
type EmailAddress struct {
	Value string `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
}

func (m *EmailAddress) Reset()                    { *m = EmailAddress{} }
func (m *EmailAddress) String() string            { return proto.CompactTextString(m) }
func (*EmailAddress) ProtoMessage()               {}
func (*EmailAddress) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *EmailAddress) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*ServiceConfig)(nil), "istio.mixer.v1.config.ServiceConfig")
	proto.RegisterType((*AspectRule)(nil), "istio.mixer.v1.config.AspectRule")
	proto.RegisterType((*Aspect)(nil), "istio.mixer.v1.config.Aspect")
	proto.RegisterType((*Adapter)(nil), "istio.mixer.v1.config.Adapter")
	proto.RegisterType((*GlobalConfig)(nil), "istio.mixer.v1.config.GlobalConfig")
	proto.RegisterType((*ClientConfig)(nil), "istio.mixer.v1.config.ClientConfig")
	proto.RegisterType((*Uri)(nil), "istio.mixer.v1.config.Uri")
	proto.RegisterType((*IpAddress)(nil), "istio.mixer.v1.config.IpAddress")
	proto.RegisterType((*DnsName)(nil), "istio.mixer.v1.config.DnsName")
	proto.RegisterType((*EmailAddress)(nil), "istio.mixer.v1.config.EmailAddress")
}

func init() { proto.RegisterFile("mixer/v1/config/cfg.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 579 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x93, 0x41, 0x6b, 0xd4, 0x40,
	0x14, 0xc7, 0xc9, 0xa6, 0x9b, 0xb4, 0x6f, 0xb7, 0x54, 0x56, 0xc5, 0xb8, 0x58, 0xa9, 0xb9, 0x58,
	0x0f, 0x26, 0xee, 0x6a, 0x41, 0x05, 0x85, 0xb5, 0x2d, 0x52, 0x50, 0xd1, 0x16, 0x2f, 0x22, 0x94,
	0xd9, 0xc9, 0x6b, 0x18, 0x3b, 0xc9, 0xc4, 0x99, 0xc9, 0x62, 0x6f, 0x7e, 0x39, 0xc1, 0x8f, 0x25,
	0x99, 0x24, 0xdd, 0xd8, 0x6d, 0xb3, 0x45, 0xf0, 0x38, 0x93, 0xf7, 0xfb, 0xcd, 0x9b, 0xc9, 0xff,
	0xc1, 0xdd, 0x84, 0xfd, 0x40, 0x19, 0xce, 0x46, 0x21, 0x15, 0xe9, 0x09, 0x8b, 0x43, 0x7a, 0x12,
	0x07, 0x99, 0x14, 0x5a, 0x0c, 0x6e, 0x33, 0xa5, 0x99, 0x08, 0x4c, 0x41, 0x30, 0x1b, 0x05, 0x65,
	0xc1, 0xf0, 0x5e, 0x2c, 0x44, 0xcc, 0x31, 0x34, 0x45, 0xd3, 0xfc, 0x24, 0x54, 0x5a, 0xe6, 0x54,
	0x97, 0xd0, 0x70, 0xe7, 0xa2, 0x2f, 0x42, 0x45, 0x25, 0xcb, 0xb4, 0x90, 0x21, 0x17, 0xf1, 0x31,
	0xa6, 0x5a, 0x9e, 0x1d, 0xcf, 0x37, 0x2b, 0x6c, 0xdc, 0x82, 0x25, 0xa8, 0x25, 0xa3, 0x8b, 0xcc,
	0xeb, 0x36, 0x46, 0xa4, 0x4c, 0x0b, 0x89, 0xd1, 0xb1, 0x44, 0x25, 0x72, 0x49, 0x71, 0x91, 0x6f,
	0x6b, 0x35, 0x93, 0x2c, 0xa5, 0x2c, 0x23, 0x7c, 0x11, 0x1b, 0xb5, 0x60, 0xdf, 0x73, 0xa1, 0xc9,
	0x02, 0xe2, 0x47, 0xb0, 0x7e, 0x84, 0x72, 0xc6, 0x28, 0xee, 0x1a, 0x64, 0xb0, 0x01, 0xae, 0xca,
	0xa7, 0xdf, 0x90, 0x6a, 0xcf, 0xda, 0xb2, 0xb6, 0xd7, 0x06, 0x37, 0x60, 0x55, 0xe2, 0x8c, 0x29,
	0x26, 0x52, 0xaf, 0x63, 0x76, 0x9e, 0x40, 0x57, 0xe6, 0x1c, 0x95, 0x67, 0x6f, 0xd9, 0xdb, 0xbd,
	0xf1, 0x83, 0xe0, 0xd2, 0xbf, 0x11, 0x4c, 0x54, 0x86, 0x54, 0x1f, 0xe6, 0x1c, 0xfd, 0x9f, 0x16,
	0xc0, 0x7c, 0x59, 0x28, 0x15, 0x72, 0xa4, 0x5a, 0xc8, 0xea, 0x90, 0x00, 0x5c, 0x62, 0xbe, 0x2b,
	0xaf, 0x63, 0xa4, 0x9b, 0xad, 0xd2, 0x7f, 0x68, 0xe1, 0xb7, 0x05, 0x4e, 0x05, 0xf7, 0x61, 0xe5,
	0x94, 0xa5, 0x51, 0x75, 0xf4, 0x06, 0xb8, 0x24, 0x22, 0x99, 0x46, 0x59, 0x5d, 0xef, 0x05, 0x38,
	0x2c, 0xcd, 0x72, 0x5d, 0xcb, 0x1f, 0xb5, 0xca, 0x83, 0x03, 0x53, 0xbb, 0x5f, 0x84, 0x67, 0xf0,
	0x10, 0x9c, 0x8c, 0x48, 0x92, 0x28, 0x6f, 0x65, 0xcb, 0xda, 0xee, 0x8d, 0xef, 0x04, 0x65, 0x22,
	0x83, 0x3a, 0x91, 0xc1, 0x91, 0x49, 0x64, 0xd1, 0x42, 0x4a, 0x12, 0xf4, 0xba, 0xc5, 0x89, 0xc3,
	0xc7, 0xd0, 0x6b, 0x5a, 0x7a, 0x60, 0x9f, 0xe2, 0x59, 0xd5, 0xde, 0x3a, 0x74, 0x67, 0x84, 0xe7,
	0x58, 0x36, 0xf7, 0xb2, 0xf3, 0xdc, 0xf2, 0xbf, 0x82, 0x3b, 0x29, 0x3b, 0x3e, 0xf7, 0x94, 0xb5,
	0xf5, 0xc5, 0x3a, 0xf5, 0x8a, 0x25, 0x19, 0xf7, 0x6c, 0xb3, 0xba, 0x6e, 0x6b, 0xfe, 0x2f, 0x1b,
	0xfa, 0x6f, 0xb9, 0x98, 0x12, 0x5e, 0x25, 0xa2, 0x19, 0x00, 0xab, 0x0a, 0xc0, 0x6a, 0xf5, 0x64,
	0xf5, 0xef, 0xba, 0x7f, 0xd5, 0x1b, 0x55, 0x7d, 0xbe, 0x81, 0x15, 0x2e, 0xe2, 0xfa, 0x45, 0x9f,
	0x5d, 0x51, 0xdd, 0x48, 0xe7, 0x3b, 0x11, 0x9b, 0xc7, 0xd8, 0x3b, 0xdf, 0x1a, 0xec, 0x82, 0x5b,
	0xce, 0x5b, 0x71, 0x85, 0x42, 0x33, 0x5e, 0xae, 0x79, 0x6f, 0x80, 0x86, 0xe4, 0x0b, 0xdc, 0x5c,
	0x1c, 0x40, 0xe5, 0x75, 0x8d, 0xf0, 0xd5, 0x35, 0x84, 0x35, 0x7c, 0x58, 0xb1, 0x0d, 0xf7, 0x01,
	0xc0, 0xf9, 0x70, 0x2a, 0xcf, 0x31, 0xca, 0x9d, 0xe5, 0xca, 0x8f, 0x35, 0xd3, 0x50, 0x4d, 0xc0,
	0x31, 0x03, 0xab, 0x3c, 0xd7, 0x68, 0x46, 0xcb, 0x35, 0x9f, 0x8a, 0xfa, 0xb9, 0xc2, 0xa7, 0xd0,
	0xdf, 0xe5, 0x0c, 0x53, 0xfd, 0x3f, 0x07, 0xfb, 0x16, 0xd8, 0x9f, 0x25, 0x9b, 0x87, 0xd4, 0x98,
	0xfd, 0x21, 0xac, 0x1d, 0x64, 0x93, 0x28, 0x92, 0xa8, 0xd4, 0xdf, 0xdf, 0xfa, 0xbe, 0x07, 0xee,
	0x5e, 0xaa, 0x3e, 0x90, 0x04, 0x2f, 0x52, 0x9b, 0xd0, 0xdf, 0x4f, 0x08, 0xe3, 0x97, 0x82, 0x6b,
	0x53, 0xc7, 0x04, 0xf5, 0xe9, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x45, 0x70, 0x2e, 0xb2, 0x17,
	0x06, 0x00, 0x00,
}
