handlers:
- name: versionList
  adapter: genericListChecker
  params:
    listEntries: ["v1", "v2"]

- name: prometheusLocal
  adapter: "prometheus"
  params:
    mixerPort: 42422

- name: redisQuotaLocal
  adapter: redisQuota
  params:
    redisURL: redis://localhost:9789/2

- name: loggerLocal
  adapter: stdioLogger
  params:
    log_stream: STDOUT

