handlers:
- name: versionList
  genericListChecker_params:
    listEntries: ["v1", "v2"]

- name: prometheusLocal
  prometheus_params:
    mixerPort: 42422

- name: redisQuotaLocal
  redisQuota_params:
    redisURL: redis://localhost:9789/2

- name: loggerLocal
  stdioLogger_params:
    log_stream: STDOUT

