// WARNING !! CURRENTLY THIS IS HARD CODED AND NOT AUTOGENERATED !!

// Copyright 2017 Istio Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// THIS FILE IS AUTOMATICALLY GENERATED.

package metric

import "istio.io/mixer/configs/templates/metric"

type Instance struct {
  Value      interface{}
  Dimensions map[string]interface{}
}

type MetricProcessor interface {
  ConfigureMetric(templateName string, types map[string]*istio_mixer_adapter_metric.Type /*typeName to Type mapping*/) error
  ReportMetric(templateName string, instances map[string]*Instance /*typeName to Instance (generated from Constructor) mapping*/) (error)
}

